### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by gaceladri** [VITA-Group/BERT-Tickets#2]
Hello,

I have extracted the GraSP algorithm from here:
https://github.com/VITA-Group/BERT-Tickets/blob/master/transformers-master/examples/GraSP.py

I am getting CUDA out of memory on whatever size my architecture have. I have migrated your version of transformers to the new one. 

Here is my trainer.py script:
https://gist.github.com/gaceladri/f301f33779785c401c8c1e549bcc1144

I have just adapted your pretrain_grasp.py to the trainer.py script on Transformers 3.3.1

The error comes at the backward pass in the (2) iteration:
https://github.com/VITA-Group/BERT-Tickets/blob/c55e3d9ed21c4a66a58de0f3d1a0d64ca7f73653/pretrain_grasp.py#L729

Could it be that we are doing the backward pass with the main model loaded and we are duplicating the weights?

Thanks

**Comment by gaceladri** [comment]
Well it could be that I have a GTX1070 TI and It does not support sparse opperations. I solved it doing the work on cpu but then I didnt know how to use the saved mask.

**Comment by Tianlong-Chen** [comment]
Thanks for the interest in our repo. I think the GraSP failed on the BERT model pruning. Thus I did not include the GraSP results in our paper. I am going to delete it and re-clean. We will release it in our next work.

For how to use the saved mask, I will refer to the original repo https://github.com/alecwangcq/GraSP. We follow their implementation and only change the model and dataset.

Thanks!

**Comment by gaceladri** [comment]
Thanks for your answer. I assumed that my GPU cannot work with sparse kernels and I went to the 'cpu'. It worked but I got stucked on using the mask. I left it for future work. Thanks! Neat work!
